apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3NhYXMtcHJpdmF0ZS5kdWNrZG5zLm9yZyI6eyJ1c2VybmFtZSI6ImFkbWludXNlciIsInBhc3N3b3JkIjoiTHNhYXMxMkAiLCJhdXRoIjoiWVdSdGFXNTFjMlZ5T2t4ellXRnpNVEpBIn19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: helm-secret
type: kubernetes.io/dockerconfigjson
